version: 2.1


jobs:  
  deployment-and-api-tests:    
    build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:   
      - checkout  
      - run:
          name: 'Intro'
          command:
            'echo testing all examples in /examples against test suite in /test'     
      - run:
          name: Deploy Mock APP for Regstration BB API and PyTest Containers
          command: cd examples/mock && ./test_entrypoint.sh
      - run:
          name: Check Status of Mock App and API-Testing Containers
          command: docker ps
      
      - run:
          name: Run cucumber tests against Register BB Mock 
          command: docker  exec -i pytest  pytest 
                
                

    
workflows:  
  deployment-and-api-tests:    
    jobs:      
      - deployment-and-api-tests:
          filters:            
            branches:
              only:
                - master

